#!/bin/bash
# Lets see machine specifications and environments
df -h
free -h
nproc
cat /etc/os*
env

# First build cant download ccache, how can it! ccache gets collected after atleast 1 build! So no need to provide url for first bulid.
url= # Where cccahe is located, use your ones, from where you want to download ccache!

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50 # Using aria2c for speed haha, ccache will be at /tmp/ccache.tar.gz since my file name is ccache.tar.gz
time tar xf ccache.tar.gz  # Extract ccache so ci can use it
rm -rf ccache.tar.gz # Remove unnecessary downloaded file, it will speed up the upload ccache process
