#!/bin/bash

git config --global  user.name "aseelsathar"
git config --global  user.email "aseelsathar@gmail.com"

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init -q --no-repo-verify --depth=1 -u git://github.com/DotOS/manifest.git -b dot11 -g default,-device,-mips,-darwin,-notdefault

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8

#device
git clone https://github.com/aseelps/device_xiaomi_juice --single-branch -b DotOS device/xiaomi/juice
git clone https://github.com/MiCode/Xiaomi_Kernel_OpenSource --single-branch -b lime-q-oss kernel/xiaomi/juice

rm -rf hardware/qcom-caf/wlan
git clone https://android.googlesource.com/platform/hardware/qcom/wlan hardware/qcom-caf/wlan


